services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/nosqli_hunter
    depends_on:
      - mongo
